### ISSUE TITLE
Support to es2015 (es6) modules

### ISSUE THREAD

**Issue by tiagofabre** [bucharest-gold/szero#104]
Since ES2015 modules are being extensively used with build tools and recently Chrome canary announced support for them [[ Chrome Canary - ES2015 modules]](https://twitter.com/addyosmani/status/859296190323597313), I consider szero must support this modules and make the life of the developers easier.

**Comment by lholmquist** [comment]
I'm going to put a future label on this.

while es modules are coming to chrome canary, it will probably still be a while before they come to node.  Also, there is still a lot of debate on how they will actually work in node land.  

I would say if you are currently trying to use es modules in Node, then you will most likely be transpiling your code, so to use szero, then you would probably need to put it at the end of the transpilation

**Comment by tiagofabre** [comment]
To use szero only in the code after build is not the same experience of use it in a 'pure' node project since the output normally hasn't package.json, and even if szero detect the package.json the output will show wrong data about lines of usages.

To show how hard is that I did this tutorial:
https://github.com/tiagofabre/HowHardIsToUseSZeroWithTranspiledCode

To show how hard is to use szero with transpiled code folloe that:

    npm isntall -g szero

    git glone https://github.com/tiagofabre/HowHardIsToUseSZeroWithTranspiledCode.git

    cd HowHardIsToUseSZeroWithTranspiledCode/

    npm install

    npm run build 

    szero ./build

the output is:

    package.json is require
    
    (node:35014) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: package.json is require
    
    (node:35014) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


Does that project has intention to search dependencies of front end projects? or just 'pure' node projects?
It is a really important question since there is not just front-end projects to consider we also have isomorphic and universal apps.

**Comment by helio-frota** [comment]
> Does that project has intention to search dependencies of front end projects? or just 'pure' node projects?

Hi @tiagofabre, sorry the late reply. The initial idea is that would to be used on non-front-end projects.
That does not mean it can not work one day in the future.
But it is not or was not the initial purpose.

**Comment by helio-frota** [comment]
closing this, we can reopen in a future in case needed.
