### ISSUE TITLE
api for Programmatic use

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#16]
We need to create an entry point, like index.js, that exports the api so someone could use it in code

**Comment by lholmquist** [comment]
just thinking out loud and i haven't actually looked at what the reporter is returning, so this might be there already

- [ ] reporter should probably return a JSON Object

**Comment by helio-frota** [comment]
Good, we can create kind of 'jsonReport' since I'm almost finishing 'fileReport' with same layout as console report.

**Comment by helio-frota** [comment]
functions 'extracted' for better reuse

https://github.com/bucharest-gold/szero/blob/master/lib/reporter.js

**Comment by lholmquist** [comment]
yay,  landed in 7ce94bd
