### ISSUE TITLE
flag for which reporters to use

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#21]
I believe currently when the command is run, both reporters(console and file) are run.

I think this should change a little bit, since this will affect #16 .  Here is my suggestion.

When run from the command line, it should default to just do console output and if some flag is provided, maybe like `--reporter=file` or something like that,  then it will also do the file reporter.

When calling the api directly, console and file reporters are not run(i'll create a future issue about also returning a file in the api) and just the JSON object is returned.  

@helio-frota any strong objections or agreements :)

**Comment by helio-frota** [comment]
@lholmquist agree :+1:

**Comment by lholmquist** [comment]
landed here: 21ceb4b
