### ISSUE TITLE
Possibly Add Commander for better arg parsing

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#34]
with more flags being added, i wonder if it is time to add a more sophisticated parsing tool like commander, https://www.npmjs.com/package/commander.

i add the issue for adding a --help flag #32 , using commander would give us this for free, 

Looks like it only had 1 dependency and that dependency has no dependencies 

If we like this idea, then i can set it up for the next milestone

**Comment by helio-frota** [comment]
:+1:

**Comment by lholmquist** [comment]
landed in bacd283
