### ISSUE TITLE
Document API Methods and options

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#40]
Need to add some jsdoc type stuff to document the API

**Comment by lholmquist** [comment]
docs landed here:  611894a  

will wait to close this once we get gh pages turned on

**Comment by lholmquist** [comment]
docs are now here: https://bucharest-gold.github.io/szero/module-szero.html

**Comment by lance** [comment]
@lholmquist Can you add the relevant link in the README.md metadata?

**Comment by lholmquist** [comment]
@lance should be on master now
