### ISSUE TITLE
Consider adding license information

### ISSUE THREAD

**Issue by jaredsmith** [bucharest-gold/szero#42]
Would you please consider adding licensing information about each dependency, so that it's easy to scan a program and tell which licenses are getting pulled in by each dependency?

**Comment by helio-frota** [comment]
@jaredsmith thanks for the issue suggestion!

![a](https://cloud.githubusercontent.com/assets/6443576/19818752/8f3f2906-9d27-11e6-8ffb-e27408e67ac0.png)

https://www.npmjs.com/package/szero

**Comment by helio-frota** [comment]
We are going to remove the `license` feature and we have plans to use a more complete and accurate license lookup/scan solution: https://github.com/bucharest-gold/license-reporter/issues/258
