### ISSUE TITLE
license info optional 

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#43]
related to https://github.com/bucharest-gold/szero/issues/42 , i wonder if showing the license info should be behind a flag?  We are doing a GET for each of the dependencies, so for a project with lots of dependencies, it could take a while.

@helio-frota @jaredsmith @lance thoughts?

I'll create this as another issue, but we should also have the ability to output that license info in the public API(maybe also behind a flag).

**Comment by helio-frota** [comment]
Good! :+1:

**Comment by jaredsmith** [comment]
I'm fine with it being a flag to show the license information.

**Comment by lholmquist** [comment]
@jaredsmith @helio-frota ok,  this PR https://github.com/bucharest-gold/szero/pull/46 should add the flag( `-l` or `--license` )
