### ISSUE TITLE
Promise rejection handler warning

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#47]
While running in Node 7, There is a test that produces the 

    (node:80749) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): package.json is require

    (node:80749) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

we should probably fix that.  Not sure if  it is the test or the lib that is the issue

**Comment by lholmquist** [comment]
now here:   dbe60f8

**Comment by tiagofabre** [comment]
Why is this closed? To change the input will only hide the warning, but the problem stills there. 

To solve this issue we need to handle the rejection of promise just like that:

`
run(program.args[0], options).catch(error) { throw error };
`
