### ISSUE TITLE
License as [object object]

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/szero#50]
Found on huilu build: 
https://travis-ci.org/bucharest-gold/huilu/jobs/173071772#L424

**Comment by lholmquist** [comment]
oh yea,  i guess we can't assume a String here.

**Comment by lholmquist** [comment]
reference on the license property: https://docs.npmjs.com/files/package.json#license

it says that using an object or array is deprecated,  but of course it still used.

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/szero/commit/5b214b594f3f72eb91d862b14122e1eb2d21b807

```
----------------------------------------------------------------------
[ Licenses ]
----------------------------------------------------------------------
concat-stream --> MIT
cpuprofilify --> MIT  [ fixed ]
handlebars --> MIT
through2 --> MIT
xtend --> MIT
```
