### ISSUE TITLE
Problem with same require but different usage

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/szero#70]
```
require('../index.js')
require('../index')
```

This is the same file, but since node do a cache, we need to keep only one.
Suggestion to keep `require('../index.js')` or what is with the nearest path.

szero is using a Set so if we do a `require('foo')` inside `A.js`
When szero found another `require('foo')` inside `B.js` it will be discarded automatically due Set.
So we need also to solve the issue with relative path like:

```
require('../index.js')
require('../../index')
require('../../../index')
require('../../../../index.js')
```
Because the Set will will treat this as different elements.

**Comment by helio-frota** [comment]
to reproduce:
clone this repo, install szero globally and run `szero .` 
https://github.com/helio-frota/foo-szero

**Comment by helio-frota** [comment]
> Modules are cached after the first time they are loaded. This means (among other things) that every call to require('foo') will get exactly the same object returned, if it would resolve to the same file.

https://nodejs.org/api/modules.html#modules_caching

**Comment by tiagofabre** [comment]
Sorry, I misunderstood the problem 🙈

**Comment by helio-frota** [comment]
yeah, also was my fault, and due this I wrote the https://github.com/helio-frota/foo-szero to clarify.
Using a file solves the issue but we lost things like require('someModule').

From [the example](https://github.com/helio-frota/foo-szero), all relative paths without a specified directory like **a**/index.js or **b**/index.js ,
I mean, all the requires with only **..** are pointing to the same index.js file.
Then, maybe some bits of logic around the strings of the elements of the Set may solve the issue.
(I'm not 100% sure)

**Comment by tiagofabre** [comment]
Is there a problem if the output changes ? because to check if they are the same I am resolving the path as you can see in this commit: [# path fix](https://github.com/tiagofabre/szero/commit/e335ae49d29d54a280e9dff805927c524e6cf4b3)

**Comment by helio-frota** [comment]
@tiagofabre I've updated the foo-szero example to show the modules not related to file :

`require('../index.js'),require('roi'),require('fidelity'),require('./a/index.js'),`
https://github.com/helio-frota/foo-szero#foo-szero
