### ISSUE TITLE
Ignore commented requires

### ISSUE THREAD

**Issue by tiagofabre** [bucharest-gold/szero#75]
szero is tracking commented requires but it is not something expected since that modules are not being loaded from node and it is not using resources.

My test to check if a commented module is being tracked was to comment a require and checked if it is in the output of szero.

``` javascript
const indexOnRootDirectoryRequiredFromC = require('../index.js');
const indexOnRootDirectoryRequiredFromD = require('./d/index.js');
// const indexOnRootDirectoryRequiredFromD = require('../a/commentedModule.js');
/* const indexOnRootDirectoryRequiredFromE = require('../a/commentedModule1.js'); */
```

and my output was

require('../index.js'),
require('./d/index.js'),
**require('../a/commentedModule.js')**
**require('../a/commentedModule1.js')**

**Comment by helio-frota** [comment]
bucharest-gold/entente#133

**Comment by helio-frota** [comment]
https://github.com/bucharest-gold/szero/commit/e9f2ae4dee992126cb6de8547df50b5adf10f2d4
