### ISSUE TITLE
--flag for DevDependencies

### ISSUE THREAD

**Issue by lholmquist** [bucharest-gold/szero#8]
Should we add a flag for also searching for usage of development Dependencies?

**Comment by helio-frota** [comment]
feel free.

**Comment by helio-frota** [comment]
part of
https://github.com/bucharest-gold/szero/commit/4d77ca74edd43ff3ee15025d9465cb649ec9d7b8

**Comment by helio-frota** [comment]
I think is good to close this issue and create another for report.
