### ISSUE TITLE
Ignore devDependencies

### ISSUE THREAD

**Issue by evanshortiss** [bucharest-gold/szero#95]
Just installed szero in a new project where I'm using a few items from `devDependencies` as CLI tools in my `scripts` section of the `package.json` -`eslint` for example. Since `eslint` is not required in any tests `szero` flags it as an issue.

I'm wondering should there be a way to pass a list of dependencies to ignore? Or maybe a flag to say ignore `devDependencies` entirely?

**Comment by evanshortiss** [comment]
Just noticed that `devDependencies` are supposed to be ignored unless `--dev` is passed to this tool, so I think there's a small bug to track down in `szero@0.9.2`. Might have time to take a look.

**Comment by helio-frota** [comment]
thanks for the feedback.
I was trying to replicate using this: 
https://github.com/helio-frota/foo-szero 
but looks like is working for this ^
but this do not means that szero don't have a bug...
also maybe is good to add this "foo-project" as test on szero, and ofc refactor the "fixtures"

we have:
https://github.com/bucharest-gold/szero/tree/master/test/fixtures
and this:
https://github.com/bucharest-gold/szero/tree/master/sample_project

I think that would be great to keep only the "sample_project" by adding the other tests cases from the "fixtures" directory **+** that `foo-szero` project, to get a more organized unit tests and to be more easy to add a new unit tests and test cases.

**Comment by helio-frota** [comment]
@evanshortiss hi !
Can you please add your case on `sample_project` ?
https://github.com/bucharest-gold/szero/tree/master/sample_project
thanks!

**Comment by evanshortiss** [comment]
@helio-frota hey, I recreated with the sample project:

```
git clone git@github.com:helio-frota/foo-szero.git
cd foo-szero/
szero --version
0.9.2
szero ./ --summary

----------------------------------------------------------------------
[ Unused dependencies ]
----------------------------------------------------------------------
fidelity,request,roi,eslint,eslint-config-semistandard,eslint-config-standard,eslint-plugin-promise,eslint-plugin-react,eslint-plugin-standard,szero
----------------------------------------------------------------------
[ Missing dependencies ]
----------------------------------------------------------------------
None.
```

Looks like `devDependencies` are not being ignored.

**Comment by evanshortiss** [comment]
Actually, turns out it is a bug in the `--summary` option. If I do not add `--summary` I get this correct output:

```
szero .
----------------------------------------------------------------------
[ Declaration and file lines ]
----------------------------------------------------------------------
----------------------------------------------------------------------
[ Declaration and amount ]
----------------------------------------------------------------------
----------------------------------------------------------------------
[ Unused dependencies ]
----------------------------------------------------------------------
fidelity
request
roi
----------------------------------------------------------------------
[ Requires ]
----------------------------------------------------------------------
a/index.js
b/index.js
c/d/index.js
c/index.js
index
index.js
Require count --> 6
```

**Comment by helio-frota** [comment]
@evanshortiss good ! 
I'm going to close this issue here and create another. 
Thanks !
